[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'rhysd/vim-textobj-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'joker1007/vim-ruby-heredoc-syntax'
on_ft = ['ruby']
depends = ['vim-coffee-script']

[[plugins]]
repo = 'c-brenn/phoenix.vim'
on_ft = ['elixir']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'coffee']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'coffee']

[[plugins]]
repo = 'briancollins/vim-jst'
on_ft = ['javascript']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'burnettk/vim-angular'
on_ft = ['javascript', 'coffee']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['scss']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'vim-scripts/nginx.vim'
on_ft = ['nginx']

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
depends = ['tabular']
hook_add = '''
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_new_list_item_indent = 2
'''

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown']
depends = ['vim-coffee-script']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['dockerfile']

[[plugins]]
repo = 'thoughtbot/vim-rspec'
on_ft = ['ruby.rspec']
depends = ['vim-dispatch']
hook_add = '''
  if executable("bin/rspec")
    let g:rspec_command = "Dispatch bin/rspec {spec}"
  else
    let g:rspec_command = "Dispatch bundle exec rspec {spec}"
  endif
  nmap <silent><leader>c :call RunCurrentSpecFile()<CR>
  nmap <silent><leader>n :call RunNearestSpec()<CR>
  nmap <silent><leader>l :call RunLastSpec()<CR>
  nmap <silent><leader>a :call RunAllSpecs()<CR>
'''

[[plugins]]
repo = 'elixir-lang/vim-elixir'
