[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/unite.vim'
hook_source = 'call unite#define_source(s:unite_git_conflicts)'
hook_source = ':au BufEnter * :call ChangeCurrentDirectoryToRoot()'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
depends = ['unite.vim']
on_source = ['unite.vim']

[[plugins]]
repo = 'sorah/unite-ghq'
depends = ['unite.vim']
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'glidenote/memolist.vim'
depends = ['unite.vim']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'thoughtbot/vim-rspec'
on_ft = ['ruby']
depends = ['vim-dispatch']

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'rhysd/vim-textobj-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'joker1007/vim-ruby-heredoc-syntax'
on_ft = ['ruby']
depends = ['vim-coffee-script']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'coffee']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'coffee']

[[plugins]]
repo = 'briancollins/vim-jst'
on_ft = ['javascript']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'burnettk/vim-angular'
on_ft = ['javascript', 'coffee']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['scss']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'vim-scripts/nginx.vim'
on_ft = ['nginx']
